= Enonic XP - Menu App

This application is an extension of the https://developer.enonic.com/docs/guillotine/stable/api[Guillotine GraphQL API].
If the Guillotine application is installed on your XP instance, then after installing this application, a `getMenu(contentKey: String!): Menu` field will be added to the https://developer.enonic.com/docs/guillotine/stable/api#headlesscms[HeadlessCms] type.

== API
=== MenuItem

==== Fields

|===
|Name(Arguments):Type | Description

|id: String
|ID of the content.

|title: String
|Title of the menu item. If the menu has a `menuName` in the config, this will be used. Otherwise, the `displayName` from the content will be used.

|path: String
|Path of the content.

|name: String
|Name of the content.

|type: String
|Type of the content.

|url(type: https://developer.enonic.com/docs/guillotine/stable/api#urltype[UrlType]): String
|Url of the content.

|content: https://developer.enonic.com/docs/guillotine/stable/api#content[Content]
|Relevant content.

|children: [<<MenuItem>>]
|Submenu items.
|===

=== Menu

==== Fields

|===
|Name(Arguments):Type | Description

|menuItems: [<<MenuItem>>]
|Returns a menu for the content with the given key.
|===

== Usage

To start using this in Guillotine, simply add the menu field with the necessary sub-fields to your GraphQL query:

```graphql
fragment menuItemFields on MenuItem {
    title
    path
    name
    url(type: absolute)
    id
    type
}

fragment menuFields on MenuItem {
    ...menuItemFields
    children {
        ...menuItemFields
        children {
            ...menuItemFields
        }
    }
}

query {
    guillotine(project: "hmdb", branch: "draft") {
        getMenu(contentKey: "/hmdb/movies")  {
            menuItems {
                ...menuFields
            }
        }
    }
}
```

In this example, we are querying the menu for the content with the key `/hmdb/movies`.
To retrieve a specific number of submenus, you can use the `children` field. In our case three levels of submenus are retrieved.
