= Enonic XP - Menu App

This application extends the https://developer.enonic.com/docs/guillotine/stable/api#headlesscms[HeadlessCms type from Guillotine GraphQL API] with a `menu: Menu` field.

The `menu` field will be added after installing this app and can be used to retrieve a menu for a specific site.

```
type HeadlessCms {
    ...
    menu: Menu
}
```

== API
=== MenuItem

==== Fields

|===
|Name(Arguments):Type | Description

|title: String
|Title of the menu item. If the menu has a `menuName` in the config, this will be used. Otherwise, the `displayName` from the content will be used.

|path: String
|Menu relative path for specific content.

|name: String
|Name of the content.

|content: https://developer.enonic.com/docs/guillotine/stable/api#content[Content]
|Relevant content.

|items: [<<MenuItem>>]
|Submenu items.
|===

=== Menu

==== Fields

|===
|Name(Arguments):Type | Description

|items: [<<MenuItem>>]
|Returns a menu for the specific site.
|===

== Usage

To start using this in Guillotine, simply add the menu field with the necessary sub-fields to your GraphQL query:

```graphql
fragment menuItemFields on MenuItem {
    title
    path
    name
    content {
        _id
    }
}

fragment menuFields on MenuItem {
    ...menuItemFields
    items {
        ...menuItemFields
        items {
            ...menuItemFields
        }
    }
}

query {
    guillotine {
       menu  {
          items {
             ...menuFields
          }
       }
    }
}
```

If the `X-Guillotine-SiteKey` header is set, the menu will be retrieved for the given site. Otherwise, the menu will be retrieved for project.

To retrieve a specific number of submenus, you can use the `items` field. In our case three levels of submenus are retrieved.

== Migration from Menu Lib

To migrate from Menu Lib to Menu App, you can follow these steps:

1. Install the Menu App. This app includes x-data called `menu-item`.
2. In Content Studio edit all content items which were marked as menu items for the Menu Lib: uncheck the "Show in menu" checkbox in the `Menu Settings` x-data provided by the Menu Lib and check off the checkbox in the "Menu" x-data provided by the Menu App.
3. Rewrite your menu code to use the new GraphQL API. See the example of usage above.
4. Remove Menu Lib from your project.
