= Enonic XP - Menu App

This application extends the https://developer.enonic.com/docs/guillotine/stable/api#headlesscms[HeadlessCms type from Guillotine GraphQL API] with a `menu: Menu` field.

The `menu` field will be added after installing this app and can be used to retrieve a menu for a specific site.

```
type HeadlessCms {
    ...
    menu: Menu
}
```

== API
=== MenuItem

==== Fields

|===
|Name(Arguments):Type | Description

|id: String
|ID of the content.

|title: String
|Title of the menu item. If the menu has a `menuName` in the config, this will be used. Otherwise, the `displayName` from the content will be used.

|path: String
|Path of the content.

|name: String
|Name of the content.

|type: String
|Type of the content.

|content: https://developer.enonic.com/docs/guillotine/stable/api#content[Content]
|Relevant content.

|children: [<<MenuItem>>]
|Submenu items.
|===

=== Menu

==== Fields

|===
|Name(Arguments):Type | Description

|menuItems: [<<MenuItem>>]
|Returns a menu for the specific site.
|===

== Usage

To start using this in Guillotine, simply add the menu field with the necessary sub-fields to your GraphQL query:

```graphql
fragment menuItemFields on MenuItem {
    title
    path
    name
    id
    type
}

fragment menuFields on MenuItem {
    ...menuItemFields
    children {
        ...menuItemFields
        children {
            ...menuItemFields
        }
    }
}

query {
    guillotine {
       menu  {
           menuItems {
             ...menuFields
          }
       }
    }
}
```

If the `X-Guillotine-SiteKey` header is set, the menu will be retrieved for the given site. Otherwise, the menu will be retrieved for project.

To retrieve a specific number of submenus, you can use the `children` field. In our case three levels of submenus are retrieved.
